name: sbp
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - notebook=6.4.3
  - numpy=1.21.2
  - pandas=1.3.3
  - pip=21.2.4
  - scipy=1.7.1
  - setuptools=58.0.4
  - jupyterlab=3.1.7
  - python=3.8
  - pip:
      - segyio==1.9.7
      - gstools==1.3
      - git+https://github.com/devitocodes/devito.git@a7e2553
      - -e code
